### PR TITLE
odpi/egeria#6907 master->main rename

### PR DESCRIPTION
**Pull request by planetf1**
Signed-off-by: Nigel Jones <nigel.l.jones+git@gmail.com>

Updating master->main

### CODE REVIEW

**Comment by planetf1** [comment]
@alexandra-bucur @lpalashevski This PR is to update some code refs for 'master' to use 'main' instead.

However I note that all PR builds are failing currently. I initially saw a memory issue, so I changed the mem available for tests. However I continue to get a test failure

Is this something you are aware of?

**Comment by alexandra-bucur** [comment]
Hi @planetf1! The failure of the tests is related to some changes that were added in Egeria's models. I added the new fields in the mappers, but they are inside #777. Can this PR wait for a review on the other one?

**Comment by lpalashevski** [comment]
Yes. @planetf1 please put the rename for this repo on hold until we fix the build with #777. Thanks!

**Comment by planetf1** [comment]
@lpalashevski The rename is already done for the repository.

This PR is just to update files within the repository & build script. We'll need to get just the build updated so we can push through the cicd changes - or you can cherry-pick the commits here into your proposal

**Pull request merged**
